# Generated by Django 5.0.2 on 2024-03-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comments_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='parents',
            new_name='parent',
        ),
    ]
